### ISSUE TITLE
AttributeError: 'SpellChecker' object has no attribute '_enabled'

### ISSUE THREAD

**Issue by jamiemcg** [koehlma/pygtkspellcheck#27]
Recently having the following problem with pygtkspellcheck. It no longer works at all, the error below is thrown when you right click on a word. Any ideas what's causing it?

Using Ubuntu 16.04, Python 3.5.1
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 496, in _click_move_button
    if self._deferred_check:  self._check_deferred_range(True)
AttributeError: 'SpellChecker' object has no attribute '_deferred_check'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 154, in <lambda>
    self._view.connect('populate-popup', lambda entry, menu: self._extend_menu(menu))
  File "/usr/lib/python3/dist-packages/gtkspellcheck/spellcheck.py", line 452, in _extend_menu
    if not self._enabled:
AttributeError: 'SpellChecker' object has no attribute '_enabled'
```

**Comment by koehlma** [comment]
Hey, it seems to me, that you are using an old version. Are you using the Ubuntu/Debian package?
