### ISSUE TITLE
installation problem of gi

### ISSUE THREAD

**Issue by lordmax** [koehlma/pygtkspellcheck#35]
Hi

I'm new to python and I need pygtkspellchecker for a project

I work with python 3.6

When I try to install (via pip or package tar.gz) it ends with this error:

```
Processing c:\users\enrico\downloads\cloud\py\pygtkspellcheck-4.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Enrico\AppData\Local\Temp\pip-2dlfzfrd-build\setup.py", line 44, in <module>
        import gtkspellcheck
      File "C:\Users\Enrico\AppData\Local\Temp\pip-2dlfzfrd-build\src\gtkspellcheck\__init__.py", line 52, in <module>
        from gtkspellcheck.spellcheck import (SpellChecker, NoDictionariesFound,
      File "C:\Users\Enrico\AppData\Local\Temp\pip-2dlfzfrd-build\src\gtkspellcheck\spellcheck.py", line 59, in <module>
        from gi.repository import Gtk as gtk
      File "C:\Users\Enrico\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gi\__init__.py", line 39
        print url
                ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Enrico\AppData\Local\Temp\pip-2dlfzfrd-build\
```

I've tried to uninstall python 2 times, I've tried to install python on a directory under root but nothign.
Someone can help me?

Thanks

**Comment by koehlma** [comment]
It seems to me that this is due to an installed version of GI which is not compatible with Python 3. I would suggest to uninstall all installed versions of Python and delete all directories including `C:\Users\Enrico\AppData\Local\Programs\Python`. Since this is not an issue with Python GTK Spellcheck itself I will close this.
