### ISSUE TITLE
The libraries pyenchant and pygtkspellcheck failed to install for Zim on macOS

### ISSUE THREAD

**Issue by gusbemacbe** [koehlma/pygtkspellcheck#37]
Hello,

Please, read:

1. https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/165

I followed @reagle's instructions from the e-mail:

2. https://lists.launchpad.net/zim-wiki/msg04519.html

But it still gave the same errors:

```
/usr/local/bin/pip2 install pyenchant pyxdg pygtkspellcheck
Collecting pyenchant
  Using cached pyenchant-1.6.11-py2.py3.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp33.pp35-none-macosx_10_6_intel.macosx_10_9_intel.whl
Collecting pyxdg
  Using cached pyxdg-0.25.tar.gz
Collecting pygtkspellcheck
  Using cached pygtkspellcheck-4.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    build_sphinx command is unavailable, please install Sphinx to solve this
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-ezvRSE/pygtkspellcheck/setup.py", line 44, in <module>
        import gtkspellcheck
      File "/private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-ezvRSE/pygtkspellcheck/src/gtkspellcheck/__init__.py", line 52, in <module>
        from gtkspellcheck.spellcheck import (SpellChecker, NoDictionariesFound,
      File "/private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-ezvRSE/pygtkspellcheck/src/gtkspellcheck/spellcheck.py", line 26, in <module>
        import enchant
    ImportError: No module named enchant
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/53/ml1f4dtd38x5l0y7v6grrj6m0000gn/T/pip-build-ezvRSE/pygtkspellcheck/
```

**Comment by koehlma** [comment]
Thank for reporting! This is the same as #36. It is relatively easy to fix, but my Linux machine is broken at the time being. As a quick fix: Try to install Enchant first and then Python GTK Spellcheck, i.e.:
```
pip install pyenchant
pip install pygtkspellcheck
```

**Comment by gusbemacbe** [comment]
Oh my Alderaan, it worked now.
