### ISSUE TITLE
No longer builds from flatpak when switched in for old version

### ISSUE THREAD

**Issue by cheywood** [koehlma/pygtkspellcheck#48]
Build fails, presumably due to missing Sphinx.

I'm mainly checking in that this is expected behaviour? Triggered by your April 25 changes.

```
[...]
Running: python3 setup.py install --prefix=/app --root=/
build_sphinx command is unavailable, please install Sphinx to solve this
Traceback (most recent call last):
  File "/run/build/pygtkspellcheck/setup.py", line 69, in <module>
    read_variables()
  File "/run/build/pygtkspellcheck/setup.py", line 66, in read_variables
    raise RuntimeError("Unable to find {} string".format(src))
RuntimeError: Unable to find __short_name__ string
Error: module pygtkspellcheck: Child process exited with code 1
```

**Comment by koehlma** [comment]
The problem is not with Sphinx but with parsing the metadata from the `__init__.py` file (presumably due to the change in formatting caused by using Black). Can you try to use `pip install .` instead?

Actually, I think, `setup.py` should be completely dropped in favor of `pyproject.toml`.

**Comment by cheywood** [comment]
Thanks, I'll have a look at that when I can grab another moment (a quick prod hit a pause when flatpak wasn't finding Rust to compile crypography for poetry)

**Comment by cheywood** [comment]
How much of a headache would retaining `setup.py` support for now be?

It seems for Flatpak users there will be a hurdle or two to jump at the moment as [flatpak-pip-generator](https://docs.flatpak.org/en/latest/python.html) doesn't appear to gracefully handle Poetry at the moment. Perhaps keeping `setup.py` support for the moment could bridge the gap until things move more smoothly on that end.

**Comment by cheywood** [comment]
I've got Flatpak, Pip, Poetry and Rust (for the cryptography) module playing along together now :+1: 

If that's the path forward and setup.py isn't working, setup.py should be removed?

Also, I found a typo in my last PR, blocking the release, will send a fix tomorrow.

**Comment by cheywood** [comment]
> Also, I found a typo in my last PR, blocking the release, will send a fix tomorrow.

See #49.

My hopefully last set of thoughts on Flatpak, `setup.py`, Poetry, etc: I haven't checked if the way I'm doing this with Flatpak will result in a download size impact or any runtime impacts. It still feels a bit odd to bring in a dependency on Rust for something extrinsic to pygtkspellcheck. I guess if there were still a `setup.py` option I (and I imagine others) might go for that.

Naturally there's a chance I've gone about this the wrong way!

Hopefully all is now closer to a release. I'll use some test builds with the integrated changes over the next few days and let you know if I hit anything.

**Comment by cheywood** [comment]
Just FYI hitting an issue with the Cryptography build for aarch64 now, which I'll need to look at later

**Comment by koehlma** [comment]
Sorry for the delayed response, I have been quite busy the last week.

The dependency on Poetry (and therefore Rust) should only be necessary when building Python GTK Spellcheck from source. I will release a wheel to PyPi and then this should not be necessary when installing via `pip`. I would expect almost everyone to use the wheel and not build it from source.

I can publish an RC version which you could use instead of building from source.

**Comment by cheywood** [comment]
No worries at all.

This all makes a bit more sense :+1: If you're able to do the RC I'll give it some more testing.

**Comment by koehlma** [comment]
Here you go: https://pypi.org/project/pygtkspellcheck/5.0.0rc0/

**Comment by cheywood** [comment]
Brilliant, thanks. Back up and running on aarch64 :smile:
